import ClubModel from '../models/Club.js';

const databaseClubs: ClubModel[] = [
    {
        id: 1,
        name: 'Manchester City',
        country: 'England',
        fundation: 1880,
        champions: 1,
    },
    {
        id: 2,
        name: 'Inter Milan',
        country: 'Italy',
        fundation: 1908,
        champions: 3,
    },
    {
        id: 3,
        name: 'Real Madrid',
        country: 'Spain',
        fundation: 1902,
        champions: 14,
    },
    {
        id: 4,
        name: 'AC Milan',
        country: 'Italy',
        fundation: 1899,
        champions: 7,
    },
    {
        id: 5,
        name: 'Bayern Munich',
        country: 'Germany',
        fundation: 1900,
        champions: 6,
    },
    {
        id: 6,
        name: 'Chelsea',
        country: 'England',
        fundation: 1905,
        champions: 2,
    },
    {
        id: 7,
        name: 'Paris Saint-Germain',
        country: 'France',
        fundation: 1970,
        champions: 0,
    },
    {
        id: 8,
        name: 'Benfica',
        country: 'Portugal',
        fundation: 1904,
        champions: 2,
    },
    {
        id: 9,
        name: 'Napoli',
        country: 'Italy',
        fundation: 1926,
        champions: 0,
    },
    {
        id: 10,
        name: 'Liverpool',
        country: 'England',
        fundation: 1892,
        champions: 6,
    },
    {
        id: 11,
        name: 'Borussia Dortmund',
        country: 'Germany',
        fundation: 1909,
        champions: 1,
    },
    {
        id: 12,
        name: 'Tottenham Hotspur',
        country: 'England',
        fundation: 1882,
        champions: 0,
    },
    {
        id: 13,
        name: 'FC Porto',
        country: 'Portugal',
        fundation: 1893,
        champions: 2,
    },
    {
        id: 14,
        name: 'RB Leipzig',
        country: 'Germany',
        fundation: 2009,
        champions: 0,
    },
    {
        id: 15,
        name: 'Club Brugge',
        country: 'Belgium',
        fundation: 1891,
        champions: 0,
    },
    {
        id: 16,
        name: 'Atletico Madrid',
        country: 'Spain',
        fundation: 1903,
        champions: 0,
    },
    {
        id: 17,
        name: 'Ajax',
        country: 'Netherlands',
        fundation: 1900,
        champions: 4,
    },
    {
        id: 18,
        name: 'Barcelona',
        country: 'Spain',
        fundation: 1899,
        champions: 5,
    },
    {
        id: 19,
        name: 'Bayer Leverkusen',
        country: 'Germany',
        fundation: 1904,
        champions: 0,
    },
    {
        id: 20,
        name: 'Eintracht Frankfurt',
        country: 'Germany',
        fundation: 1899,
        champions: 0,
    },
];

export default databaseClubs;
