import PlayerModel from '../models/Player.js';

const databasePlayers: PlayerModel[] = [
    {
        id: 1,
        name: 'Kevin De Bruyne',
        age: 32,
        club: 'Manchester City',
        nationality: 'Belgium',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 91,
            pace: 76,
            shooting: 86,
            passing: 93,
            dribbling: 88,
            defending: 64,
            physical: 77,
        },
    },
    {
        id: 2,
        name: 'Erling Haaland',
        age: 24,
        club: 'Manchester City',
        nationality: 'Norway',
        position: 'Forward',
        foot: 'Left',
        statistics: {
            overall: 91,
            pace: 89,
            shooting: 94,
            passing: 73,
            dribbling: 80,
            defending: 45,
            physical: 88,
        },
    },
    {
        id: 3,
        name: 'Rúben Dias',
        age: 27,
        club: 'Manchester City',
        nationality: 'Portugal',
        position: 'Defender',
        foot: 'Right',
        statistics: {
            overall: 89,
            pace: 67,
            shooting: 48,
            passing: 73,
            dribbling: 70,
            defending: 88,
            physical: 86,
        },
    },
    {
        id: 4,
        name: 'Thibaut Courtois',
        age: 32,
        club: 'Real Madrid',
        nationality: 'Belgium',
        position: 'Goalkeeper',
        foot: 'Right',
        statistics: {
            overall: 90,
            pace: 44,
            shooting: 22,
            passing: 44,
            dribbling: 46,
            defending: 15,
            physical: 83,
        },
    },
    {
        id: 5,
        name: 'Luka Modrić',
        age: 38,
        club: 'Real Madrid',
        nationality: 'Croatia',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 89,
            pace: 71,
            shooting: 77,
            passing: 89,
            dribbling: 90,
            defending: 70,
            physical: 68,
        },
    },
    {
        id: 6,
        name: 'Vinícius Júnior',
        age: 23,
        club: 'Real Madrid',
        nationality: 'Brazil',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 89,
            pace: 95,
            shooting: 83,
            passing: 79,
            dribbling: 92,
            defending: 35,
            physical: 72,
        },
    },
    {
        id: 7,
        name: 'Rodrygo',
        age: 23,
        club: 'Real Madrid',
        nationality: 'Brazil',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 85,
            pace: 88,
            shooting: 82,
            passing: 79,
            dribbling: 89,
            defending: 45,
            physical: 61,
        },
    },
    {
        id: 8,
        name: 'Robert Lewandowski',
        age: 35,
        club: 'FC Barcelona',
        nationality: 'Poland',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 91,
            pace: 78,
            shooting: 93,
            passing: 79,
            dribbling: 85,
            defending: 43,
            physical: 82,
        },
    },
    {
        id: 9,
        name: 'Joshua Kimmich',
        age: 29,
        club: 'Bayern Munich',
        nationality: 'Germany',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 89,
            pace: 69,
            shooting: 74,
            passing: 89,
            dribbling: 84,
            defending: 83,
            physical: 76,
        },
    },
    {
        id: 10,
        name: 'Harry Kane',
        age: 31,
        club: 'Bayern Munich',
        nationality: 'England',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 90,
            pace: 70,
            shooting: 93,
            passing: 82,
            dribbling: 84,
            defending: 47,
            physical: 83,
        },
    },
    {
        id: 11,
        name: 'Jude Bellingham',
        age: 21,
        club: 'Real Madrid',
        nationality: 'England',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 78,
            shooting: 78,
            passing: 79,
            dribbling: 84,
            defending: 77,
            physical: 82,
        },
    },
    {
        id: 12,
        name: 'Bernardo Silva',
        age: 29,
        club: 'Manchester City',
        nationality: 'Portugal',
        position: 'Midfielder',
        foot: 'Left',
        statistics: {
            overall: 88,
            pace: 77,
            shooting: 76,
            passing: 83,
            dribbling: 92,
            defending: 62,
            physical: 69,
        },
    },
    {
        id: 13,
        name: 'Jack Grealish',
        age: 28,
        club: 'Manchester City',
        nationality: 'England',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 80,
            shooting: 75,
            passing: 82,
            dribbling: 88,
            defending: 50,
            physical: 72,
        },
    },
    {
        id: 14,
        name: 'Mohamed Salah',
        age: 32,
        club: 'Liverpool',
        nationality: 'Egypt',
        position: 'Forward',
        foot: 'Left',
        statistics: {
            overall: 90,
            pace: 90,
            shooting: 88,
            passing: 81,
            dribbling: 90,
            defending: 45,
            physical: 75,
        },
    },
    {
        id: 15,
        name: 'Virgil van Dijk',
        age: 32,
        club: 'Liverpool',
        nationality: 'Netherlands',
        position: 'Defender',
        foot: 'Right',
        statistics: {
            overall: 90,
            pace: 79,
            shooting: 60,
            passing: 71,
            dribbling: 72,
            defending: 91,
            physical: 86,
        },
    },
    {
        id: 16,
        name: 'Alisson Becker',
        age: 31,
        club: 'Liverpool',
        nationality: 'Brazil',
        position: 'Goalkeeper',
        foot: 'Right',
        statistics: {
            overall: 89,
            pace: 52,
            shooting: 30,
            passing: 58,
            dribbling: 48,
            defending: 15,
            physical: 86,
        },
    },
    {
        id: 17,
        name: 'Andy Robertson',
        age: 30,
        club: 'Liverpool',
        nationality: 'Scotland',
        position: 'Defender',
        foot: 'Left',
        statistics: {
            overall: 87,
            pace: 84,
            shooting: 66,
            passing: 80,
            dribbling: 80,
            defending: 81,
            physical: 76,
        },
    },
    {
        id: 18,
        name: 'Karim Benzema',
        age: 36,
        club: 'Real Madrid',
        nationality: 'France',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 91,
            pace: 80,
            shooting: 90,
            passing: 82,
            dribbling: 88,
            defending: 39,
            physical: 78,
        },
    },
    {
        id: 19,
        name: 'Federico Valverde',
        age: 26,
        club: 'Real Madrid',
        nationality: 'Uruguay',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 88,
            pace: 88,
            shooting: 80,
            passing: 81,
            dribbling: 84,
            defending: 79,
            physical: 83,
        },
    },
    {
        id: 20,
        name: 'Sandro Tonali',
        age: 24,
        club: 'Newcastle United',
        nationality: 'Italy',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 85,
            pace: 73,
            shooting: 71,

            passing: 80,
            dribbling: 82,
            defending: 83,
            physical: 82,
        },
    },
    {
        id: 21,
        name: 'Bruno Fernandes',
        age: 29,
        club: 'Manchester United',
        nationality: 'Portugal',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 88,
            pace: 74,
            shooting: 84,
            passing: 88,
            dribbling: 83,
            defending: 68,
            physical: 77,
        },
    },
    {
        id: 22,
        name: 'Marcus Rashford',
        age: 26,
        club: 'Manchester United',
        nationality: 'England',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 85,
            pace: 91,
            shooting: 82,
            passing: 77,
            dribbling: 84,
            defending: 43,
            physical: 75,
        },
    },
    {
        id: 23,
        name: 'Rafael Leão',
        age: 25,
        club: 'AC Milan',
        nationality: 'Portugal',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 87,
            pace: 92,
            shooting: 80,
            passing: 73,
            dribbling: 89,
            defending: 34,
            physical: 77,
        },
    },
    {
        id: 24,
        name: 'Olivier Giroud',
        age: 37,
        club: 'AC Milan',
        nationality: 'France',
        position: 'Forward',
        foot: 'Left',
        statistics: {
            overall: 83,
            pace: 51,
            shooting: 83,
            passing: 71,
            dribbling: 77,
            defending: 39,
            physical: 79,
        },
    },
    {
        id: 25,
        name: 'André Onana',
        age: 28,
        club: 'Manchester United',
        nationality: 'Cameroon',
        position: 'Goalkeeper',
        foot: 'Right',
        statistics: {
            overall: 84,
            pace: 54,
            shooting: 27,
            passing: 75,
            dribbling: 46,
            defending: 12,
            physical: 76,
        },
    },
    {
        id: 26,
        name: 'Romelu Lukaku',
        age: 31,
        club: 'Inter Milan',
        nationality: 'Belgium',
        position: 'Forward',
        foot: 'Left',
        statistics: {
            overall: 86,
            pace: 82,
            shooting: 83,
            passing: 70,
            dribbling: 75,
            defending: 35,
            physical: 86,
        },
    },
    {
        id: 27,
        name: 'Lautaro Martínez',
        age: 26,
        club: 'Inter Milan',
        nationality: 'Argentina',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 87,
            pace: 85,
            shooting: 83,
            passing: 75,
            dribbling: 87,
            defending: 45,
            physical: 80,
        },
    },
    {
        id: 28,
        name: 'Nicolò Barella',
        age: 27,
        club: 'Inter Milan',
        nationality: 'Italy',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 78,
            shooting: 73,
            passing: 82,
            dribbling: 85,
            defending: 78,
            physical: 74,
        },
    },
    {
        id: 29,
        name: 'André Silva',
        age: 28,
        club: 'RB Leipzig',
        nationality: 'Portugal',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 83,
            pace: 77,
            shooting: 81,
            passing: 71,
            dribbling: 79,
            defending: 40,
            physical: 74,
        },
    },
    {
        id: 30,
        name: 'Christopher Nkunku',
        age: 26,
        club: 'Chelsea',
        nationality: 'France',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 85,
            shooting: 84,
            passing: 82,
            dribbling: 88,
            defending: 47,
            physical: 72,
        },
    },
    {
        id: 31,
        name: 'Pedri',
        age: 21,
        club: 'FC Barcelona',
        nationality: 'Spain',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 75,
            shooting: 68,
            passing: 87,
            dribbling: 90,
            defending: 71,
            physical: 62,
        },
    },
    {
        id: 32,
        name: 'Frenkie de Jong',
        age: 27,
        club: 'FC Barcelona',
        nationality: 'Netherlands',
        position: 'Midfielder',
        foot: 'Right',
        statistics: {
            overall: 88,
            pace: 81,
            shooting: 72,
            passing: 85,
            dribbling: 88,
            defending: 77,
            physical: 78,
        },
    },
    {
        id: 33,
        name: 'Gavi',
        age: 20,
        club: 'FC Barcelona',
        nationality: 'Spain',
        position: 'Midfielder',
        foot: 'Left',
        statistics: {
            overall: 83,
            pace: 74,
            shooting: 67,
            passing: 80,
            dribbling: 83,
            defending: 75,
            physical: 77,
        },
    },
    {
        id: 34,
        name: 'Phil Foden',
        age: 24,
        club: 'Manchester City',
        nationality: 'England',
        position: 'Midfielder',
        foot: 'Left',
        statistics: {
            overall: 86,
            pace: 82,
            shooting: 78,
            passing: 82,
            dribbling: 89,
            defending: 54,
            physical: 64,
        },
    },
    {
        id: 35,
        name: 'Raphaël Varane',
        age: 31,
        club: 'Manchester United',
        nationality: 'France',
        position: 'Defender',
        foot: 'Right',
        statistics: {
            overall: 85,
            pace: 79,
            shooting: 47,
            passing: 65,
            dribbling: 65,
            defending: 87,
            physical: 80,
        },
    },
    {
        id: 36,
        name: 'Serge Gnabry',
        age: 29,
        club: 'Bayern Munich',
        nationality: 'Germany',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 84,
            pace: 87,
            shooting: 83,
            passing: 77,
            dribbling: 84,
            defending: 45,
            physical: 73,
        },
    },
    {
        id: 37,
        name: 'Dayot Upamecano',
        age: 25,
        club: 'Bayern Munich',
        nationality: 'France',
        position: 'Defender',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 81,
            shooting: 48,
            passing: 70,
            dribbling: 74,
            defending: 86,
            physical: 85,
        },
    },
    {
        id: 38,
        name: 'Giovanni Di Lorenzo',
        age: 30,
        club: 'Napoli',
        nationality: 'Italy',
        position: 'Defender',
        foot: 'Right',
        statistics: {
            overall: 84,
            pace: 82,
            shooting: 60,
            passing: 76,
            dribbling: 79,
            defending: 81,
            physical: 80,
        },
    },
    {
        id: 39,
        name: 'Victor Osimhen',
        age: 25,
        club: 'Napoli',
        nationality: 'Nigeria',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 88,
            shooting: 85,
            passing: 65,
            dribbling: 80,
            defending: 40,
            physical: 82,
        },
    },
    {
        id: 40,
        name: 'Khvicha Kvaratskhelia',
        age: 23,
        club: 'Napoli',
        nationality: 'Georgia',
        position: 'Forward',
        foot: 'Right',
        statistics: {
            overall: 86,
            pace: 90,
            shooting: 78,
            passing: 81,
            dribbling: 89,
            defending: 39,
            physical: 67,
        },
    },
];

export default databasePlayers;
